# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenuWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.leftMenuWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.leftMenuWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.leftMenuWidget.setObjectName("leftMenuWidget")
        self.tabSchemas = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabSchemas.sizePolicy().hasHeightForWidth())
        self.tabSchemas.setSizePolicy(sizePolicy)
        self.tabSchemas.setObjectName("tabSchemas")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabSchemas)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetBut = QtWidgets.QWidget(self.tabSchemas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetBut.sizePolicy().hasHeightForWidth())
        self.widgetBut.setSizePolicy(sizePolicy)
        self.widgetBut.setMinimumSize(QtCore.QSize(0, 0))
        self.widgetBut.setObjectName("widgetBut")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetBut)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonBack = QtWidgets.QPushButton(self.widgetBut)
        self.buttonBack.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBack.sizePolicy().hasHeightForWidth())
        self.buttonBack.setSizePolicy(sizePolicy)
        self.buttonBack.setMinimumSize(QtCore.QSize(32, 32))
        self.buttonBack.setObjectName("buttonBack")
        self.horizontalLayout_2.addWidget(self.buttonBack)
        self.buttonAdd = QtWidgets.QPushButton(self.widgetBut)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAdd.sizePolicy().hasHeightForWidth())
        self.buttonAdd.setSizePolicy(sizePolicy)
        self.buttonAdd.setMinimumSize(QtCore.QSize(16, 16))
        self.buttonAdd.setObjectName("buttonAdd")
        self.horizontalLayout_2.addWidget(self.buttonAdd)
        self.buttonAddDir = QtWidgets.QPushButton(self.widgetBut)
        self.buttonAddDir.setMinimumSize(QtCore.QSize(16, 16))
        self.buttonAddDir.setObjectName("buttonAddDir")
        self.horizontalLayout_2.addWidget(self.buttonAddDir)
        self.widget_2 = QtWidgets.QWidget(self.widgetBut)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.widgetBut)
        self.schemasList = QtWidgets.QListWidget(self.tabSchemas)
        self.schemasList.setDragEnabled(True)
        self.schemasList.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.schemasList.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.schemasList.setObjectName("schemasList")
        self.verticalLayout.addWidget(self.schemasList)
        self.leftMenuWidget.addTab(self.tabSchemas, "")
        self.tabItems = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabItems.sizePolicy().hasHeightForWidth())
        self.tabItems.setSizePolicy(sizePolicy)
        self.tabItems.setObjectName("tabItems")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tabItems)
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.itemsView = QtWidgets.QListWidget(self.tabItems)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemsView.sizePolicy().hasHeightForWidth())
        self.itemsView.setSizePolicy(sizePolicy)
        self.itemsView.setDragEnabled(True)
        self.itemsView.setObjectName("itemsView")
        self.horizontalLayout_3.addWidget(self.itemsView)
        self.leftMenuWidget.addTab(self.tabItems, "")
        self.horizontalLayout.addWidget(self.leftMenuWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.action111 = QtWidgets.QAction(MainWindow)
        self.action111.setObjectName("action111")
        self.action222 = QtWidgets.QAction(MainWindow)
        self.action222.setObjectName("action222")
        self.menuFile.addAction(self.action111)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action222)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.leftMenuWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Production planner"))
        self.buttonBack.setText(_translate("MainWindow", "<<"))
        self.buttonAdd.setText(_translate("MainWindow", "Add"))
        self.buttonAddDir.setText(_translate("MainWindow", "Dir"))
        self.leftMenuWidget.setTabText(self.leftMenuWidget.indexOf(self.tabSchemas), _translate("MainWindow", "Schemas"))
        self.leftMenuWidget.setTabText(self.leftMenuWidget.indexOf(self.tabItems), _translate("MainWindow", "Items"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.action111.setText(_translate("MainWindow", "111"))
        self.action222.setText(_translate("MainWindow", "222"))

